//
// Created by aron on 17-11-15.
//

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef INSTALLMENT_ANDROID_MD5_UTIL_LIB_H
#define INSTALLMENT_ANDROID_MD5_UTIL_LIB_H

#define SALT "salt_al_douzi"
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     Java_io_silvrr_installment_jni_Encrypt_Encrypt
 * Method:    md5Encode
 */

JNIEXPORT jstring JNICALL Java_io_silvrr_installment_jni_Encrypt_Encrypt_md5SaltEncode
        (JNIEnv *, jclass, jstring, jboolean, jboolean);

#ifdef __cplusplus
}
#endif
#endif

